spring:
  application:
    name: abixen-platform-core
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    generate-ddl: true
  cache:
    ehcache:
      config: classpath:ehcache.xml